language: node_js
node_js:
- '0.10'
services:
- mongodb
script:
  - istanbul cover mocha

deploy:
  provider: heroku
  api_key:
    secure: b33S9s4C0dXvWCI0rutSs3VMF0aFNRIcwp1l/JmbHFaNVia5Gx9pZD3P0X0xVUCy1LUdgveRJW5MjjAve2erJTH7mfGAdKmI+mOHtTxPV19PSsRgLM43q22gn4p8jXaxBrJ4QtLtAuchYpYqIKvO16zrnnfEsjyDUiTC3k5VtAYmuHnq/3bgBIlx7tj1qsLaAwbAiOIajy9E7vBCD6Bm34jzmMW6I5YKbqspFe0wTdUI50J759uJmIAYIqyS4S3Rc+ZCMd7rlqXz8G0IITrNJrWJvyrF/mrhRluts5XbHnFcr9+6+MXlX3mnMU5nmkp9fYP5adRn7TZcsfT+CoAdVJ+6Sy6LF6OjXkAVKC+IM2rusb3f8tbwLPMG48tXBP4xbHgn8EjeM8Ed+PkSupTlKwjr9b2vwE/kUl4guNxGe2YS4qQT19NtHj3rW+BWRBFzOwlL+7QvQ/59s8xysKDUSIsqD/Ca5PqPHyqoH9JY2XG+jJNHJ929dmD9SxA/qo39YYOVxQo3pM4f/X0/IYBZ4JRN1XQfjwSSR2YBkzS3GdQol2zNIp2E72jJQuWHU2zbYF39syYP/V6vogtNSKD/GZoG0Y8+9dkarMpadN5ptY4RVQy6ycqSvEAL7gLBTtOQqOdNTJ2C32NPO6EHu4tuvcOnKNeiTDwlZkpdMiqZWBM=
